import {RoleType} from "./user-role.type";

export type UserType = {
	userId: string;
	companyId: string;
	userNm: string;
	userPw: string;
	empNo: string;
	isUsed: boolean;
	isRestricted: boolean;
	roleId: string;
	loginFailCount?: number | null;
	email?: string | null;
	extEmail?: string | null;
	isEmailSubscribed: boolean;
	createdAt?: Date;
	updatedAt?: Date;
	deletedAt?: Date;
	role?: RoleType;
};

export type UserErpType = {
	userId?: string;
	companyId?: string;
	companyNm?: string;
	empNo?: string;
	korNm?: string;
	chnNm?: string | null;
	engNm?: string | null;
	joinDate?: string;
	groupJoinDate?: string;
	empType?: string;
	empTypeNm?: string;
	jobType?: string;
	jobTypeNm?: string;
	deptCd?: string | null;
	deptNm?: string | null;
	dutyCd?: string;
	dutyNm?: string;
	posCd?: string;
	posNm?: string;
	birthDate?: string;
	birthMonth?: string;
	lunarCalYn?: string;
	juminNo?: string;
	appointmentDate?: string;
	zipCode?: string;
	addr1?: string;
	addr2?: string | null;
	homeTel?: string | null;
	mobile?: string;
	email?: string;
	extEmail?: string | null;
	billableYn?: string;
	religion?: string | null;
	hobby?: string | null;
	bloodType?: string | null;
	photo?: string | null;
	milGroup?: string | null;
	milClass?: string | null;
	milRank?: string | null;
	milSpecialty?: string | null;
	milEnlistmentDate?: string | null;
	milDischargeDate?: string | null;
	milExemptionReason?: string | null;
	retireDate?: string;
	retireReason?: string;
	confirmYn?: string | null;
	emergencyContactNm?: string | null;
	emergencyContact?: string | null;
	leaveStartDate?: string | null;
	leaveEndDate?: string | null;
	probationEndDate?: string | null;
	marriedYn?: string;
	weddingAnniversary?: string | null;
	contractEndDate?: string | null;
	mngCompany?: string | null;
	workPeriod?: string;
	createDate?: string;
	createUser?: string | null;
	updateDate?: string | null;
	updateUser?: string | null;
	orgPath?: string | null;
	seqNum?: number;
	technicalLevel?: string | null;
	technicalLevelNm?: string | null;
	scnTechNo?: string | null;
	jobGroup?: string | null;
	jobGroupNm?: string | null;
	bankCode?: string | null;
	bankNm?: string | null;
	bankAccountNo?: string | null;
	bankAccountHolder?: string | null;
	newEmpNo?: string | null;
	connectedEmpNo?: string | null;
};
